### ISSUE TITLE
Create an abstract LDAP user service

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#16]

**Comment by p013570** [comment]
I have added an AbstractLdapUserService class. Due to the nature of different LDAP servers being configured differently, which user auths/roles being stored as different attributes, it isn't really possible to create a proper LdapUserService implementation, each LDAP server needs their own service implementation with their own logic to fetch the different parts of a User object.

The abstract class will hopefully provide some useful methods and standardise connecting to LDAP, along with a simple cache to reduce the number of calls to LDAP. However, in some cases it might be easier to just fully write your own implementation. Users don't have to use this AbstractLdapUserService class, it is just there to help with some implementations.

**Comment by p013570** [comment]
Merged into develop.
