### ISSUE TITLE
Stop erroneous error message about configuration environment variable firing during unit tests

### ISSUE THREAD

**Issue by ac74475** [gchq/Palisade#432]
Currently the Rest JUnit tests fail due to the PALISADE_REST_CONFIG_PATH system variable not being set.

**Comment by m09526** [comment]
I'm having issues reproducing this. Indications it might be a Windows specific issue?

**Comment by m09526** [comment]
The IT tests do produce an erroneous ERROR log stating an environment variable isn't present. This could be a separate issue, or we could fix it for this issue.

**Comment by m09526** [comment]
The error message is being produced in ConfigUtils.retrieveConfigurationPath() during integration tests because it expects the environment variable to have been set. This doesn't actually matter for the IT tests as they inject a test delegate anyway. We should stop this error firing during IT tests.

**Comment by m09526** [comment]
Add a <environmentVariables></environmentVariables> pair defining PALISADE_REST_CONFIG_PATH  to both the surefire and failsafe plugin configurations in the Palisade root pom.xml
